=== Ahmed-Sarmoum/XML_PHP_PROJECT/Question_2/question_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
   
   <xs:simpleType name="specType">
       <xs:restriction base="xs:string">
           <xs:pattern value="2MGL|2MGI|2MRT|1MGL|1MGI|1MRT|1L|2L|3L"></xs:pattern>
       </xs:restriction>
   </xs:simpleType> 
    <xs:simpleType name="dayType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Sunday|Monday|Tuesday|Wednesday|Thursday"></xs:pattern>
        </xs:restriction>
    </xs:simpleType> 
    <xs:simpleType name="startDate">
        <xs:restriction base="xs:time">
            <xs:enumeration value="08:00:00"/>
            <xs:enumeration value="09:00:00"/>
            <xs:enumeration value="10:00:00"/>
            <xs:enumeration value="11:00:00"/>
            <xs:enumeration value="14:00:00"/>
            <xs:enumeration value="15:00:00"/>
        </xs:restriction>
    </xs:simpleType>  
    <xs:simpleType name="endDate">
        <xs:restriction base="xs:time">
            <xs:enumeration value="09:00:00"/>
            <xs:enumeration value="10:00:00"/>
            <xs:enumeration value="11:00:00"/>
            <xs:enumeration value="12:00:00"/>  
            <xs:enumeration value="15:00:00"/>
            <xs:enumeration value="16:00:00"/>
            <xs:enumeration value="17:00:00"/>
        </xs:restriction>
    </xs:simpleType> 
    <xs:element name="seance">
       <xs:complexType>
           <xs:simpleContent>
               <xs:extension base="xs:string">
                   <xs:attribute name="day" type="dayType" use="required"></xs:attribute>
                   <xs:attribute name="start" type="startDate" use="required"></xs:attribute>
                   <xs:attribute name="end" type="endDate" use="required"></xs:attribute>
                   <xs:attribute name="teacher" type="xs:string" use="required"></xs:attribute>
                   <xs:attribute name="module" type="xs:string" use="required"></xs:attribute>
                   <xs:attribute name="salle" type="xs:string" use="required"></xs:attribute>
               </xs:extension>
           </xs:simpleContent>
       </xs:complexType>
   </xs:element> 
    <xs:element name="emploi">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="seance" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="promotion" type="specType" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element> 
    
</xs:schema>

=== Ahmed-Sarmoum/XML_PHP_PROJECT/Question_2/question_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<emploi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="question_2.xsd" promotion="2MGL">
    <seance day="Sunday" start="08:00:00" end="09:00:00" teacher="nom1" module="M1" salle="Amphi"/>
    <seance day="Sunday" start="09:00:00" end="11:00:00" teacher="nom2" module="M2" salle="2"/>
    <seance day="Sunday" start="11:00:00" end="12:00:00" teacher="nom3" module="M1" salle="Amphi"/>
    <seance day="Monday" start="11:00:00" end="12:00:00" teacher="nom4" module="M4" salle="Amphi"/>
    <seance day="Monday" start="14:00:00" end="16:00:00" teacher="nom5" module="M1" salle="5"/>
    <seance day="Tuesday" start="09:00:00" end="11:00:00" teacher="nom6" module="M2" salle="6"/>
    <seance day="Tuesday" start="11:00:00" end="12:00:00" teacher="nom7" module="M1" salle="Amphi"/>
    <seance day="Tuesday" start="14:00:00" end="15:00:00" teacher="nom8" module="M3" salle="8"/>
    <seance day="Tuesday" start="15:00:00" end="17:00:00" teacher="nom13" module="M10" salle="Amphi"/>
    <seance day="Wednesday" start="08:00:00" end="10:00:00" teacher="nom9" module="M7" salle="Amphi"/>
    <seance day="Wednesday" start="10:00:00" end="12:00:00" teacher="nom3" module="M1" salle="2"/>
    <seance day="Wednesday" start="14:00:00" end="15:00:00" teacher="nom2" module="M10" salle="Amphi"/>
    <seance day="Thursday" start="08:00:00" end="11:00:00" teacher="nom1" module="M1" salle="1"/>
</emploi>
